# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shedavail_pb2 as shedavail__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shedavail_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShedAvailServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_available_hours = channel.unary_unary(
                '/shed_avail_service.ShedAvailService/get_available_hours',
                request_serializer=shedavail__pb2.AvailabilityRequirements.SerializeToString,
                response_deserializer=shedavail__pb2.AvailabilityResponse.FromString,
                _registered_method=True)
        self.handle_schedule = channel.unary_unary(
                '/shed_avail_service.ShedAvailService/handle_schedule',
                request_serializer=shedavail__pb2.ScheduleDetails.SerializeToString,
                response_deserializer=shedavail__pb2.ScheduleResponse.FromString,
                _registered_method=True)


class ShedAvailServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_available_hours(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def handle_schedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShedAvailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_available_hours': grpc.unary_unary_rpc_method_handler(
                    servicer.get_available_hours,
                    request_deserializer=shedavail__pb2.AvailabilityRequirements.FromString,
                    response_serializer=shedavail__pb2.AvailabilityResponse.SerializeToString,
            ),
            'handle_schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.handle_schedule,
                    request_deserializer=shedavail__pb2.ScheduleDetails.FromString,
                    response_serializer=shedavail__pb2.ScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shed_avail_service.ShedAvailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shed_avail_service.ShedAvailService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShedAvailService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_available_hours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shed_avail_service.ShedAvailService/get_available_hours',
            shedavail__pb2.AvailabilityRequirements.SerializeToString,
            shedavail__pb2.AvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def handle_schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shed_avail_service.ShedAvailService/handle_schedule',
            shedavail__pb2.ScheduleDetails.SerializeToString,
            shedavail__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
